#!/usr/bin/env bash
set -ex
declare -r REMOTE_PKG_URL="https://dashboard.rg-supervision.com/download/rgsupv-darwin-x64.dmg"
declare -r TMP_DIR="$(mktemp -d)"
declare -r LOCAL_PKG_TMP_PATH="${TMP_DIR}/rgsupv-darwin-x64.dmg"
function get_app_pid() {
    local -r APP_NAME=$1
    ps -eo pid,comm | awk "/${APP_NAME}$/ {print \$1}"
}
function kill_app_by_name() {
    local -r APP_NAME=$1
    if PID=$(get_app_pid "${APP_NAME}") && [[ -n "${PID}" ]]; then
        kill -s TERM "${PID}"
        sleep 1
    fi
    if PID=$(get_app_pid "${APP_NAME}") && [[ -n "${PID}" ]]; then
        kill -s KILL "${PID}"
    fi
}
# Clean up installs having legacy names
kill_app_by_name "RGSupervision"
echo "Downloading RGSupervisioninstaller"
curl --silent --output "${LOCAL_PKG_TMP_PATH}" "${REMOTE_PKG_URL}" >/dev/null
echo "Download complete"

echo "Installing RGSupervision"
sudo hdiutil attach "${TMP_DIR}/rgsupv-darwin-x64.dmg"
sudo /Volumes/RG\ Supervision\ Installer/RG\ Supervision.app/Contents/MacOS/rgsupv --action register --login token@token.tk --password 58b8d3b651f4962be0293cc19d6e5882b1a47f36 --node "#162803" 
echo "Installation finished with exit code $?"
sudo hdiutil detach /Volumes/RG\ Supervision\ Installer

rm -rf "${TMP_DIR}"